version: "3.1"
services:
  postgres-db:
    image: some-postgresdb:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    command: postgres -c shared_buffers=512MB -c effective_cache_size=1536MB -c work_mem=2621kB -c maintenance_work_mem=128MB
    shm_size: '1gb'
